---
title: "Proteoform feature finding"
author: "Isabell Bludau"
date: "October 21th, 2018"
output:
  html_document:
    toc: true
  html_notebook:
    toc: true
  pdf_document:
    toc: true
---
# Overview
In this script we ...

# Step-by-step workflow

## Load CCprofiler package and set working directory:

```{r }
library(devtools)
#install_github("CCprofiler/CCprofiler", ref = "DA_module")
#library(CCprofiler)
if (length(grep("nas21.ethz.ch",getwd()))>0) {
  setwd("~/mysonas/CCprofiler")
  load_all()
  setwd("~/mysonas/PRPF8/analysis/output")
  knitr::opts_knit$set(root.dir = '~/mysonas/PRPF8/analysis/output')
} else {
  setwd("/Volumes/ibludau-1/CCprofiler")
  load_all()
  setwd("/Volumes/ibludau-1/PRPF8/analysis/output")
  knitr::opts_knit$set(root.dir = '/Volumes/ibludau-1/PRPF8/analysis/output')
}
```

## Load data

```{r }
peptide_traces_list <- readRDS("pepTraces_proteoformMulti.rds")
design_matrix <- readRDS("design_matrix.rda")
pepTracesSum <- readRDS("pepTracesSum.rda")
calibrationFunctions <- readRDS("calibration.rds")
filteredDataProteoformResolved <- readRDS("filteredDataProteoformResolved.rds")

proteoforms <- unique(pepTracesSum$trace_annotation[grep("_",proteoform_id)]$proteoform_id)

proteoforms_withFeature <- unique(filteredDataProteoformResolved[grep("_",proteoform_ids)]$proteoform_ids)

library(splitstackshape)

install_github("js229/Vennerable"); library(Vennerable);
library("Vennerable")

install.packages('mgsub')
library('mgsub')

#traces <- copy(pepTracesSum)
#features <- copy(filteredDataProteoformResolved)

refineProteoformsByDetectedFeatures <- function(traces, features) {
  # pepToProteoformAssignment <- subset(features, select=c("subunits_annotated","proteoform_ids", "n_proteoform_ids","protein_id"))
  pepToProteoformAssignment <- copy(features)
  subunits <- cSplit(pepToProteoformAssignment, "subunits_annotated", sep = ";", direction = "long")
  subunits[, n_unique_proteoforms := length(unique(proteoform_ids)), by="protein_id"]
  subunits[, proteoform_ids := ifelse(n_unique_proteoforms==1, protein_id, proteoform_ids)]
  subunits[, n_proteoform_ids := length(unlist(strsplit(proteoform_ids, split = ";"))), by="proteoform_ids"]
  #specialProteins <- unique(subunits[n_unique_proteoforms<n_proteoform_ids]$protein_id)
  # @todo venn problems
  specialProteins <- unique(subunits[(n_unique_proteoforms > 1)]$protein_id)
  res <- lapply(specialProteins, function(x){
    #print(x)
    data <- subunits[protein_id==x]
    proteoforms <- unique(data$proteoform_ids)
    proteoforms <- strsplit(proteoforms, split = ";")
    names(proteoforms) <- seq_len(length(proteoforms))
    c <- Venn(proteoforms)@IntersectionSets
    c <- c[which(lapply(c,length)>0)]
    #c <- calculate.overlap(proteoforms)
    #c <- c[which(lapply(c,length)>0)]
    conversionTable <- lapply(seq_along(c),function(y){
      tab <- c[[y]]
      tab <- data.table(original_id=tab)
      tab[, new_id := paste0(x,"_",y)]
    })
    conversionTable <- rbindlist(conversionTable)
    #for (z in seq_len(nrow(conversionTable))) {
    #  #data[, proteoform_ids_new := gsub(conversionTable$original_id[z], conversionTable$new[z], proteoform_ids)]
    #  data[, proteoform_ids_new := gsubfn(".", list(conversionTable$original_id = conversionTable$new_id), proteoform_ids)]
    #}
    data[, proteoform_ids := mgsub::mgsub(string = proteoform_ids,pattern = conversionTable$original_id,replacement = conversionTable$new_id)]
    data[, proteoform_ids := paste(sort(unique(unlist(strsplit(proteoform_ids, split = ";")))), collapse = ";"), by="proteoform_ids"]
    return(list(data, conversionTable))
  })
  specialProteins_res <- rbindlist(lapply(res, `[[`, 1))
  subunits <- subset(subunits, ! protein_id %in% specialProteins)
  subunits_final <- rbind(subunits, specialProteins_res)
  subunits_final[, n_unique_proteoforms := length(unique(proteoform_ids)), by="protein_id"]
  subunits_final[, proteoform_ids := ifelse(n_unique_proteoforms==1, protein_id, proteoform_ids)]
  subunits_final[, n_proteoform_ids := length(unlist(strsplit(proteoform_ids, split = ";"))), by="proteoform_ids"]
  subunits_final[, subunits_annotated_new := paste(subunits_annotated,collapse=";"), by = c("protein_id", "subunits_detected","completeness", "apex", "area", "peak_corr", "coelution_score", "qvalue")]
  subunits_final[, subunits_annotated := subunits_annotated_new]
  subunits_final[, subunits_annotated_new := NULL]
  subunits_final <- unique(subunits_final)
  
  traces_new <- copy(traces)
  conversionTable <- rbindlist(lapply(res, `[[`, 2))
  traces_new$trace_annotation <- merge(traces_new$trace_annotation, conversionTable, by.x="proteoform_id", by.y="original_id", all = TRUE, sort = FALSE)
  traces_new$trace_annotation[, new_id := ifelse(is.na(new_id), proteoform_id, new_id)]
  traces_new$trace_annotation[, proteoform_id := NULL]
  setnames(traces_new$trace_annotation, "new_id", "proteoform_id") 
  traces_new$trace_annotation[, cluster := as.integer(ifelse(length(grep("_",proteoform_id))>0,gsub(".*_","",proteoform_id),"1")), by=c("protein_id","id")]
  traces_new$trace_annotation[, n_proteoforms_beforeReassignment := n_proteoforms]
  traces_new$trace_annotation[, n_proteoforms := length(unique(proteoform_id)), by="protein_id"]
  
  return(list(traces = traces_new, features = subunits_final))
}

reassigned <- refineProteoformsByDetectedFeatures(traces = pepTracesSum, 
                                                  features = filteredDataProteoformResolved)

reassignedTraces <- reassigned[[1]]
reassignedFeatures <- reassigned[[2]]

length(unique(reassignedTraces$trace_annotation$protein_id))
length(unique(reassignedTraces$trace_annotation[n_proteoforms>1]$protein_id))
length(unique(reassignedTraces$trace_annotation[n_proteoforms>1]$protein_id))

old_traces <- copy(peptide_traces_list)

peptide_traces_list$minus$trace_annotation[,proteoform_id:=NULL]
peptide_traces_list$minus$trace_annotation[,n_proteoforms:=NULL]
peptide_traces_list$minus$trace_annotation[,cluster:=NULL]
peptide_traces_list$plus$trace_annotation[,proteoform_id:=NULL]
peptide_traces_list$plus$trace_annotation[,n_proteoforms:=NULL]
peptide_traces_list$plus$trace_annotation[,cluster:=NULL]

reassignedTraces_multi <- annotateProteoformsAcrossConditions(peptide_traces_list,
                                                              reassignedTraces)
```

## Remove peptides with no proteoform annotation

```{r }
#removeUnassignedPeptides <- function(traces){
#  proteoforms_assigned <- unique(traces$trace_annotation[!is.na(proteoform_id)]$id)
#  traces_new <- subset(traces, trace_subset_ids = proteoforms_assigned)
#  return(traces_new)
#}

#reassignedTraces_multi <- lapply(reassignedTraces_multi, removeUnassignedPeptides)
```

## Plot clusters for some example proteins

```{r }
test_proteins <- c("P22102","O00468","Q9UBF2",
                   "O15067","O75822","Q9Y266",
                   "P42167","P61978","O95801",
                   "P55060","O14578","O75717","P35221")
for (p in test_proteins){
  plotPeptideCluster(reassignedTraces_multi$minus,p)
}


#test_proteins <- unique(reassignedTraces_multi$minus$trace_annotation[n_proteoforms_beforeReassignment>n_proteoforms]$protein_id)
test_proteins <- unique(reassignedTraces$trace_annotation[n_proteoforms>1]$protein_id)[1:100]
testTraces <- subset(reassignedTraces_multi$minus, trace_subset_ids = test_proteins, trace_subset_type = "protein_id")
traces_exon_pval <- evaluateExonLocation(testTraces)

#all tested proteins
length(unique(traces_exon_pval$trace_annotation$protein_id))

# proteins with only one proteoform
length(unique(traces_exon_pval$trace_annotation[is.na(exon_pval_adj)]$protein_id))
# proteins with significant exon location p-value
length(unique(traces_exon_pval$trace_annotation[exon_pval_adj <= 0.05]$protein_id))
# proteins reaching minimum possible exon location p-value
length(unique(traces_exon_pval$trace_annotation[(exon_pval_adj > 0.05) & (exon_pval<=min_possible_pval)]$protein_id))
# proteins not explainable by exon location!
length(unique(traces_exon_pval$trace_annotation[(exon_pval_adj > 0.05) & (exon_pval>min_possible_pval)]$protein_id))



pdf(paste0("reassignedFeatures_conditionSum.pdf"),width=8,height=4)
for (id in unique(reassignedFeatures[n_proteoform_ids>1]$protein_id)[1:40]){
  plotFeatures(feature_table = reassignedFeatures,
               traces = reassignedTraces,
               calibration=calibrationFunctions,
               feature_id = id,
               annotation_label="proteoform_id",
               colour_by="proteoform_id",
               peak_area = T,
               legend = T,
               onlyBest = F)
}
dev.off()

pdf(paste0("reassignedFeatures_ORIGINAL_conditionSum.pdf"),width=8,height=4)
for (id in unique(reassignedFeatures[n_proteoform_ids>1]$protein_id)[1:40]){
  plotFeatures(feature_table = filteredDataProteoformResolved,
               traces = pepTracesSum,
               calibration=calibrationFunctions,
               feature_id = id,
               annotation_label="proteoform_id",
               colour_by="proteoform_id",
               peak_area = T,
               legend = T,
               onlyBest = F)
}
dev.off()
```


---
title: "07_proteinFeatures_proteoformResolved_reassign.R"
author: "ibludau"
date: "Wed Jan 23 14:32:37 2019"
---
